name: Build
# run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches: ["master"]
    paths-ignore:
      - "**/*.md"
      - "**/LICENSE"
      - "**/.editorconfig"
      - "**/.vscode/**"
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: Setup .NET Framework SDK
        uses: actions/setup-dotnet@v3

      - name: Write secrets to file
        run: |
          mkdir -p ~/.microsoft/usersecrets/09c442f6-0b36-4620-9fc4-bd8d8b6bc23d
          echo '${{ secrets.SECRETS_JSON }}' > ~/.microsoft/usersecrets/09c442f6-0b36-4620-9fc4-bd8d8b6bc23d/secrets.json
          sha256sum ~/.microsoft/usersecrets/09c442f6-0b36-4620-9fc4-bd8d8b6bc23d/secrets.json

      - name: Build
        run: dotnet publish backend/Backend.csproj /p:PublishProfile=backend/Properties/PublishProfiles/Linux-x64.pubxml -c Release

      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
